baseURL = "https://seokho-ham.github.io"
title = "Seokho의 개발 블로그"
copyright = "Copyright © 2021 Seokho Ham"
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-178122307-1"
theme = "LoveIt"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
[[menu.main]]
    identifier = "TIL"
    name = "TIL"
    url = "/TIL/"
    weight = 11
[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 12
[[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 13
    


[taxonomies]
algorithms = "algorithms"
category = "categories"
tag = "tags"
series = "series"
author = "author"


[params]
  author = "Seokho Ham"
  homepageImage = "/images/homepage-image.png"
  share = false
  showLanguageSwitcher = false
  mainSections = ["post"]

[sitemap] 
changefreq = "daily" 
filename = "sitemap.xml"


# Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    rss = true
    email = "kaljuice02@gmail.com"
    github = "https://github.com/Seokho-Ham"


  [params.prismJS]
    enable = true
    theme = "tomorrow"

  [params.commento]
    enable = false
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
    
[markup.goldmark.renderer]
unsafe= true